insert into cities(title, countries_id) values
('Moscow', 1),
('Saint-Petersburg', 1),
('Novosibirsk', 1),
('Yekaterinburg', 1),
('Nizhny Novgorod', 1),
('Kazan', 1),
('Chelyabinsk', 1),
('Samara', 1),
('Omsk', 1),
('Rostov-on-Don', 1),
('New York', 2),
('Los Angeles', 2),
('Chicago', 2),
('Dallas–Fort Worth', 2),
('Houston', 2),
('Washington, D.C.', 2),
('Miami', 2),
('Philadelphia', 2),
('Atlanta', 2),
('Boston', 2),
('Shanghai', 3),
('Beijing', 3),
('Chongqing', 3),
('Guangzhou', 3),
('Shenzhen', 3),
('Tianjin', 3),
('Wuhan', 3),
('Dongguan', 3),
('Hong Kong', 3),
('Mumbai', 4),
('New Delhi', 4),
('Kolkata', 4),
('Chennai', 4),
('Bangalore', 4),
('Hyderabad', 4),
('Ahmedabad', 4),
('Pune', 4),
('Berlin', 5),
('Hamburg', 5),
('Munich', 5),
('Cologne', 5),
('Frankfurt am Main', 5),
('Stuttgart', 5),
('Düsseldorf', 5),
('Dortmund', 5),
('Sao Paulo', 6),
('Rio de Janeiro', 6),
('Salvador', 6),
('Brasilia', 6),
('Fortaleza', 6),
('Belo Horizonte', 6),
('Manaus', 6),
('London', 7),
('Birmingham', 7),
('Manchester', 7),
('West Yorkshire', 7),
('North East', 7),
('Liverpool', 7),
('Sheffield', 7),
('Bristol', 7),
('Paris', 8),
('Marseille', 8),
('Lyon', 8),
('Toulouse', 8),
('Nice', 8),
('Nantes', 8),
('Strasbourg', 8),
('Montpellier', 8),
('Rome', 9),
('Milan', 9),
('Naples', 9),
('Turin', 9),
('Palermo', 9),
('Genoa', 9),
('Bologna', 9),
('Florence', 9);

