package ru.job4j.generator;

import java.util.Map;

/**
 * Generator interface.
 * @author shaplov
 * @since 19.04.2019
 */
public interface Generator {

    /**
     * Returns String generated by template and
     * incoming key-value map.
     * @param template template String.
     * @param map key-value map.
     * @return formatted String.
     */
    String generate(String template, Map<String, String> map);
}
